services:

  gameder-postgres:
    container_name: gameder-postgres
    image: postgres
    environment:
      POSTGRES_USER: gameder
      POSTGRES_PASSWORD: password
      PGDATA: /data/gameder
    volumes:
      - gameder-postgres:/data/gameder
    ports:
      - "5432:5432"
    networks:
      - gameder-postgres
    restart: unless-stopped

  gameder-pgadmin:
    container_name: gameder-pgadmin
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL:-pgadmin4@pgadmin.org}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD:-admin}
      PGADMIN_CONFIG_SERVER_MODE: 'False'
    volumes:
      - gameder-pgadmin:/var/lib/pgadmin
    ports:
      - "5050:80"
    networks:
      - gameder-postgres
    restart: unless-stopped

networks:
  gameder-postgres:
    driver: bridge

volumes:
  gameder-postgres:
  gameder-pgadmin: