services:

  gameder-postgres:
    container_name: gameder-postgres
    image: postgres
    environment:
      POSTGRES_USER: gameder
      POSTGRES_PASSWORD: password
      PGDATA: /data/gameder
    volumes:
      - gameder-postgres:/data/gameder
    ports:
      - "5432:5432"
    restart: unless-stopped

  keycloak-postgres:
    container_name: keycloak-postgres
    image: postgres
    environment:
      POSTGRES_USER: keycloak
      POSTGRES_PASSWORD: password
      PGDATA: /data/keycloak
    volumes:
      - keycloak-postgres:/data/keycloak
    ports:
      - "5433:5432"
    restart: unless-stopped

  gameder-pgadmin:
    container_name: gameder-pgadmin
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL:-pgadmin4@pgadmin.org}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD:-admin}
      PGADMIN_CONFIG_SERVER_MODE: 'False'
    volumes:
      - pgadmin:/var/lib/pgadmin
    ports:
      - "5050:80"
    restart: unless-stopped

  keycloak:
    container_name: gameder-keycloak
    image: quay.io/keycloak/keycloak:latest
    environment:
      DB_VENDOR: POSTGRES
      DB_ADDR: keycloak-postgres
      DB_DATABASE: keycloak
      DB_USER: keycloak
      DB_SCHEMA: keycloak
      DB_PASSWORD: password
      KEYCLOAK_USER: admin
      KEYCLOAK_PASSWORD: Pa55w0rd
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
      # Uncomment the line below if you want to specify JDBC parameters. The parameter below is just an example, and it shouldn't be used in production without knowledge. It is highly recommended that you read the PostgreSQL JDBC driver documentation in order to use it.
      JDBC_PARAMS: "ssl=true"
    command: "start-dev"
    ports:
      - 8180:8080
      - 8443:8443
    depends_on:
      - keycloak-postgres

volumes:
  gameder-postgres:
  keycloak-postgres:
  pgadmin: